package it.objectway.hibernate.hr.model;

// Generated Jan 27, 2015 5:26:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * EmpDetailsView generated by hbm2java
 */
public class EmpDetailsView implements java.io.Serializable {

	private EmpDetailsViewId id;

	public EmpDetailsView() {
	}

	public EmpDetailsView(EmpDetailsViewId id) {
		this.id = id;
	}

	public EmpDetailsViewId getId() {
		return this.id;
	}

	public void setId(EmpDetailsViewId id) {
		this.id = id;
	}

}
