package it.objectway.hibernate.hr.model;

// Generated Jan 27, 2015 5:26:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * JobHistory generated by hbm2java
 */
public class JobHistory implements java.io.Serializable {

	private JobHistoryId id;
	private Employees employees;
	private Jobs jobs;
	private Departments departments;
	private Date endDate;

	public JobHistory() {
	}

	public JobHistory(JobHistoryId id, Employees employees, Jobs jobs) {
		this.id = id;
		this.employees = employees;
		this.jobs = jobs;
	}

	public JobHistory(JobHistoryId id, Employees employees, Jobs jobs,
			Departments departments, Date endDate) {
		this.id = id;
		this.employees = employees;
		this.jobs = jobs;
		this.departments = departments;
		this.endDate = endDate;
	}

	public JobHistoryId getId() {
		return this.id;
	}

	public void setId(JobHistoryId id) {
		this.id = id;
	}

	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	public Jobs getJobs() {
		return this.jobs;
	}

	public void setJobs(Jobs jobs) {
		this.jobs = jobs;
	}

	public Departments getDepartments() {
		return this.departments;
	}

	public void setDepartments(Departments departments) {
		this.departments = departments;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
