package it.objectway.hibernate.hr.model;

// Generated Jan 27, 2015 5:26:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String userId;
	private Employees employees;
	private String password;
	private char enabled;

	public Users() {
	}

	public Users(String userId, Employees employees, String password,
			char enabled) {
		this.userId = userId;
		this.employees = employees;
		this.password = password;
		this.enabled = enabled;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public char getEnabled() {
		return this.enabled;
	}

	public void setEnabled(char enabled) {
		this.enabled = enabled;
	}

}
